# Go!
name: Deploy shinyapp

on:
  push
    # tags:        
      # - v0.**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
          
      - name: Deploy app
        if: contains(github.event.head_commit.message, '#deploy')
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /srv/shiny-server/
            rm -r gtfs_explorer/
            git clone git@github.com:kauebraga/gtfs_explorer.git
            systemctl restart shiny-server

