# Go!
name: Deploy shinyapp

on:
  push:
    tags:        
      - v0.**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,REGISTRY,{{ secrets.DIGITALOCEAN_ACCESS_TOKEN }},GITHUB_SHA
          
      - name: Go to shinyserver folder
        run: cd /srv/shiny-server/
        
      - name: Delete previous shinyapp
        run: rm -r gtfs_explorer/
        
      - name: Clone new app
        run: git clone git@github.com:kauebraga/gtfs_explorer.git
        
      - name: Restart shinyserver
        run: systemctl restart shiny-server
        
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
      SERVER_IP: ${{secrets.SERVER_IP}}
      CI: false  

