# Go!
name: Deploy shinyapp

on:
  push:
    tags:        
      - v0.**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
          
      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /srv/shiny-server/
            rm -r gtfs_explorer/
            git clone git@github.com:kauebraga/gtfs_explorer.git
            run: systemctl restart shiny-server

