# Go!
name: Deploy shinyapp

on:
  push
    # tags:        
      # - v0.**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
          
      - name: Deploy app
        if: contains(github.event.head_commit.message, '#deploy')
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            rm -r gtfs_explorer/
            rm -r /srv/shiny-server/gtfs_explorer
            git clone git@github.com:kauebraga/gtfs_explorer.git
            cp -r gtfs_explorer/gtfs_explorer cd /srv/shiny-server/
            systemctl restart shiny-server

